### ISSUE TITLE
Date published and date modified section is wonky

### ISSUE THREAD

**Issue by prycrane** [canada-ca/blogue-canada-ca-blog#113]
The date published and date modified section is not rendering properly at the bottom of the page.

https://deploy-preview-111--blog-tbs.netlify.app/2022/12/08/wayfinding-research-project

![image](https://user-images.githubusercontent.com/96494429/207066773-e7c4d92b-c6b2-44fe-88e0-506c551c1e16.png)

**Comment by delisma** [comment]
I see why the blog.css file has to be put back in the post if you're importing your own css. 🤔 I guess that we should bring Font Awesome at a general scale #112 first, then we could get rid of the `css` property in the front matter which would bring back the blog.css at the same time.
