### ISSUE TITLE
Broken images on https://blog.canada.ca/2019/11/01/tips-travel-contact.html

### ISSUE THREAD

**Issue by pcwsmith** [canada-ca/blogue-canada-ca-blog#136]
In the blog post https://blog.canada.ca/2019/11/01/tips-travel-contact.html, go to the section called "4. Build on previous experiments and learning." Scroll down a bit to where the images are. It looks like there are 3 screencaps missing. Did they just get moved or something?

Here's a screenshot:
<img width="768" alt="Screenshot 2023-07-13 at 12 07 15 PM" src="https://github.com/canada-ca/blogue-canada-ca-blog/assets/5454117/3051faeb-ea84-4061-90fe-19fb63419a93">

BTW, everything looks ok in the French version of the blog post.

**Comment by prycrane** [comment]
I'll check it out.
